version: '3.8'

services:
  django:
    image: python:3.9
    command: bash -c "pip install django psycopg2-binary && django-admin startproject myproject . && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=myproject
      - POSTGRES_USER=myproject
      - POSTGRES_PASSWORD=myproject
    ports:
      - 8000:8000
    restart: always
    volumes:
      - ./myproject:/app
    depends_on:
      - db

  db:
    image: postgres:alpine
    environment:
      - POSTGRES_DB=myproject
      - POSTGRES_USER=myproject
      - POSTGRES_PASSWORD=myproject
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    expose:
      - 5432

volumes:
  db_data:

